global:
  scrape_interval: 15s
  # scrape_timeout: 10s
  # evaluation_interval: 15s

# remote_write:
#   - url: http://localhost:9090/api/v1/write/

scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /actuator/prometheus
  scheme: http
  static_configs:
  - targets: ['enginebe:8080']

# - job_name: 'k6'
#   static_configs:
#   - targets: ['k6:6565']