image: openjdk:17

stages:
  - build
  - test
  - deploy

build:
  stage: build  
  script:
    - mvn clean package  

test:
  stage: test
  script:
    - mvn test 

deploy:
  stage: deploy
  script:
    - echo "Deployment stage"
